version = 1

[[annotations]]
path = [
{{EXPORT_REUSE_PATHS}}
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Monaco F. J. <https://github.com/monacofj>"
SPDX-License-Identifier = "GPL-3.0-or-later"
