#!/usr/bin/env bash

#    SPDX-FileCopyrightText: 2021 Monaco F. J. <https://github.com/monacofj>
#
#    SPDX-License-Identifier: GPL-3.0-or-later
#
#    This file is part of SYSeg - https://github.com/monacofj/syseg.


function usage()
{
    echo "Usage: $(basename "$0") [options] <file name>"
}


function help()
{
    usage
    echo
    echo "       options:"
    echo
    echo "       -f              create file if missing"
    echo "       -h              output this help message and quits"
    echo "       -v              output version and exit"
    echo
}

ORIGIN=$(dirname "$0")

template="syseg"

create_file=0
while getopts "vhf" opt; do
    case $opt in
	h)
	    help
	    exit 0
	    ;;
	v)
	    cat $ORIGIN/../.version
	    exit 0
	    ;;
	f)
	    create_file=1
	    ;;
    esac
done
shift "$(($OPTIND -1))"

FILEPATH=$1
if test -z "$FILEPATH"; then
    usage
    exit 1
fi

file_exists=0
if test -f "$FILEPATH"; then
    file_exists=1
fi

# Get origin dir (origin like in -rpath)
origin=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd) || {
    printf 'cannot determine tools directory\n' >&2
    exit 1
}

##
## Check if file exists
##

if test -f "$FILEPATH"; then
    :
elif test "$create_file" -eq 1; then
    if ! "$origin/newfile-create" "$FILEPATH"; then
        printf 'could not create file: %s\n' "$FILEPATH"
        exit 1
    fi
else
    printf 'File does not exist: %s\n' "$FILEPATH"
    printf 'use option -f to create it first.\n'
    exit 1
fi

##
## Apply copyright notice.
##


# Try to read user data

FILENAME=".newfile"

copyright=$(CDPATH= cd -- "$(dirname -- "$FILENAME")" && pwd)/$(basename -- "$FILENAME")

if ! test -f "$copyright"; then
    # If we can't find user data, try to get from Git config.
    if command -v "git" >/dev/null 2>&1; then
	name=$(git config user.name)
	email=$(git config user.email)
    else
	name='Your name\n'
	email='Your e-mail'
    fi
    printf "$name\n" > "$copyright"
    printf "$email" >> "$copyright"
    printf 'Copyright information changed; please review and then retry:\n'
    printf "$copyright\n"
    exit 1
fi

name=$(head -n 1 "$copyright")
email=$(tail -n 1 "$copyright")
year=$(date +%Y)
license="GPL-3.0-or-later"

tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT
reuse annotate -c "$name" -y "$year" -l "$license" -t "$template" "$FILEPATH" >"$tmpfile" 2>&1

status="$?"
if  test "$status" -eq 0; then
    if test "$file_exists" -eq 0; then
        printf "File created and annotated successfully: %s\n" "$FILEPATH"
    else
        printf "File updated successfully: %s\n" "$FILEPATH"
    fi
else
    cat "$tmpfile"
    if test "$file_exists" -eq 0; then
        printf "File was created but copyright notice is missing: %s\n" "$FILEPATH"
    else
        printf "File was updated but copyright notice is missing: %s\n" "$FILEPATH"
    fi
    exit 1
fi

exit 0
